

volumes:
  postgres-volume:


services:
  postgres:
    container_name: PostgreSQL
    image: postgres:alpine
    ports:
      - 5050:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user
      POSTGRES_DB: tasks
